url: 'https://alextsui05.github.io'
baseurl: 'html-sketchpad'
title: 'HTML Sketchpad'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
